export const REQ_DOG_MESSAGE = 'req_dog_message'
export const REQ_SURPRISE = 'req_surprise'
export const REQ_DOG_FOODS = 'req_dog_foods'
export const REQ_CLASSIFY = 'req_classify'
export const REQ_VERIFICATION_CODE = 'req_verification_code'
export const REQ_LOGIN = 'req_login'
export const REQ_ALL_GOODS = 'req_all_goods'
